spring.application.name=Autorent
server.port=8080

# Connexion à MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:autorent_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Identifiants
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:password123}

# Configuration JPA / Hibernate pour MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect