spring.application.name=Autorent
server.port=8080

spring.datasource.url=jdbc:sqlite:./data/autorent.db?date_string_format=yyyy-MM-dd HH:mm:ss
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

# En production on mettra une clé différentes de celle présente ici par sécurité
app.secret-key=${JWT_SECRET_KEY:9ac9d7cbe64809cfee5de175000108817d607b5b5cb9b9a395fb6fbd02573d8b}
app.expiration-time=${JWT_EXPIRATION_TIME:3600000}